/********************************************************************
* ./src/WCSimRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./src/WCSimRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableWCSimRootDict();
extern void G__cpp_setup_inheritanceWCSimRootDict();
extern void G__cpp_setup_typetableWCSimRootDict();
extern void G__cpp_setup_memvarWCSimRootDict();
extern void G__cpp_setup_globalWCSimRootDict();
extern void G__cpp_setup_memfuncWCSimRootDict();
extern void G__cpp_setup_funcWCSimRootDict();
extern void G__set_cpp_environmentWCSimRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "WCSimRootEvent.hh"
#include "WCSimRootGeom.hh"
#include "WCSimPmtInfo.hh"
#include "WCSimCHIPSPMT.hh"
#include "WCSimEvDisplay.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__WCSimRootDictLN_TClass;
extern G__linked_taginfo G__WCSimRootDictLN_TBuffer;
extern G__linked_taginfo G__WCSimRootDictLN_TMemberInspector;
extern G__linked_taginfo G__WCSimRootDictLN_TObject;
extern G__linked_taginfo G__WCSimRootDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__WCSimRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__WCSimRootDictLN_string;
extern G__linked_taginfo G__WCSimRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__WCSimRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCSimRootDictLN_TObjArray;
extern G__linked_taginfo G__WCSimRootDictLN_TClonesArray;
extern G__linked_taginfo G__WCSimRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__WCSimRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCSimRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimRootTrack;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimRootCherenkovHit;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimRootCherenkovHitTime;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimRootCherenkovDigiHit;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimRootEventHeader;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimRootPi0;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimRootTrigger;
extern G__linked_taginfo G__WCSimRootDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__WCSimRootDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimRootEvent;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimRootPMT;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimRootGeom;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimPmtInfo;
extern G__linked_taginfo G__WCSimRootDictLN_TRandom;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimCHIPSPMT;
extern G__linked_taginfo G__WCSimRootDictLN_TQObject;
extern G__linked_taginfo G__WCSimRootDictLN_TGWindow;
extern G__linked_taginfo G__WCSimRootDictLN_TGObject;
extern G__linked_taginfo G__WCSimRootDictLN_TGFrame;
extern G__linked_taginfo G__WCSimRootDictLN_TGCompositeFrame;
extern G__linked_taginfo G__WCSimRootDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__WCSimRootDictLN_TGMainFrame;
extern G__linked_taginfo G__WCSimRootDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__WCSimRootDictLN_TChain;
extern G__linked_taginfo G__WCSimRootDictLN_TH1;
extern G__linked_taginfo G__WCSimRootDictLN_TH1D;
extern G__linked_taginfo G__WCSimRootDictLN_TH2D;
extern G__linked_taginfo G__WCSimRootDictLN_TPad;
extern G__linked_taginfo G__WCSimRootDictLN_WCSimEvDisplay;

/* STUB derived class for protected member access */
